### ISSUE TITLE
Using possibility of options directly in migration scaffolding

### ISSUE THREAD

**Issue by eduardobarbiero** [rowland/activerecord-fb-adapter#57]
I wonder if the use of options directly in migrating to the database is possible.
For example:
<pre>t.string :score, options: 'CHARACTER SET ISO8859_1 COLLATE PT_BR'</pre>

Sorry if this is not the appropriate place, I'm new here ^ - ^

**Comment by rowland** [comment]
That's a good question. I think field-level options would require support at the ActiveRecord level before they could be implemented by an adapter like this one.

I'm not seeing them here:
http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/TableDefinition.html#method-i-column

**Comment by eduardobarbiero** [comment]
Hey rowland, first thanks for answering!
maybe I have fooled me a little in my question, what I say is that for example:
<pre>
create_table :users, :options => 'COLLATE=utf8_general_ci' do |t|
  t.string :email
  t.timestamps
end
</pre>
That code just above, works perfectly in mysql where the charset that set, will be the charset of the table. Maybe I'm wrong about something...
Just to be clear, this can only be possible if there is an implementation of the ActiveRecord component?

**Comment by rowland** [comment]
Perhaps I was confused by your example, which specified the collation of a column rather than a table. As a general rule, if it works for another type of adapter and the concept applies to both databases, then we should be able to support it, as the hooks should be there. I don't know that the hooks are there for field-by-field selection of char sets or collations. I could be wrong.

I would look up what kind of table-wise clauses would be applicable for Firebird, try them and see if they just work. Let us know how it goes, so one of the contributors can maybe fix it if we're close.
