### ISSUE TITLE
`Fb::Error: Invalid token` no matter what query I try

### ISSUE THREAD

**Issue by glennfu** [rowland/activerecord-fb-adapter#65]
I have a table called "DEALCONTENT" and so I have a file called `dealcontent.rb` and the first line is: `class Dealcontent < ApplicationRecord`. When I query `Dealcontent.count` I see:

    ActiveRecord::StatementInvalid: Fb::Error: Invalid token
    Dynamic SQL Error
    SQL error code = -104
    Token unknown - line 1, column 50
    "domain"
    : SELECT r.rdb$field_name name, r.rdb$field_source "domain", f.rdb$field_type type, f.rdb$field_sub_type "sub_type", f.rdb$field_length "limit", f.rdb$field_precision "precision", f.rdb$field_scale "scale", COALESCE(r.rdb$default_source, f.rdb$default_source) default_source, COALESCE(r.rdb$null_flag, f.rdb$null_flag) null_flag FROM rdb$relation_fields r JOIN rdb$fields f ON r.rdb$field_source = f.rdb$field_name WHERE r.rdb$relation_name = 'DEALCONTENT' ORDER BY r.rdb$field_position

If I call `Dealcontent.all.first` I get the same thing. What is this and how can I fix it?

**Comment by glennfu** [comment]
Also to be clear, the database connection works. If I define this:

    def self.count
      cursor = Dealcontent.connection.execute("select count(*) from Dealcontent")
      cursor.each do |row|
        return row.first
      end
    end

Then `Dealcontent.count` returns the correct number.

**Comment by glennfu** [comment]
Actually I wrote something wrong in my first post. `Dealcontent.all.first` actually returns:

    Dealcontent.all.first
    NoMethodError: undefined method `having' for #<Arel::Nodes::SelectCore:0x007f8e9e023120>
    Did you mean?  havings
                   havings=
    	from /Users/Glenn/.rvm/gems/ruby-2.3.0/gems/activerecord-fb-adapter-1.0.3/lib/arel/visitors/fb_collector.rb:70:in `visit_Arel_Nodes_SelectCore'

**Comment by glennfu** [comment]
So the `havings` vs `having` is a Rails 4 vs 5 issue. Dropping back to 4.2.6, and changing `schema_statements.rb:222` to read:

    def column_definitions(table_name)
      exec_query(squish_sql(<<-end_sql), 'SCHEMA')
        SELECT
          r.rdb$field_name name,
          r.rdb$field_source domain,
          f.rdb$field_type type,
          f.rdb$field_sub_type sub_type,
          f.rdb$field_length limit,
          f.rdb$field_scale scale,
          COALESCE(r.rdb$default_source, f.rdb$default_source) default_source,
          COALESCE(r.rdb$null_flag, f.rdb$null_flag) null_flag
        FROM rdb$relation_fields r
        JOIN rdb$fields f ON r.rdb$field_source = f.rdb$field_name
        WHERE r.rdb$relation_name = '#{ar_to_fb_case(table_name)}'
        ORDER BY r.rdb$field_position
      end_sql
    end

Now I can run all of my queries as expected! I'm very much a Firebird novice so I don't know what this means. Perhaps the FB database I'm connecting to is of a different version than this gem expects?

**Comment by rzane** [comment]
What active record version are you using?

**Comment by rzane** [comment]
Never mind. I see you were using v5 which isn't currently supported by this gem.

I've used 4.2.4 in the past, so 4.2.6 should work, but I have not tested it. What error were you getting on 4.2.6?

**Comment by glennfu** [comment]
The very first error, that's what I was getting on 4.2.6. It was an error direct from Firebird when trying to get the table's column definitions. My replacement of `def column_definitions` solved my problem.

Executing `select rdb$get_context('SYSTEM','ENGINE_VERSION') as version from RDB$DATABASE` gives "2.5.0". Do you think that explains the difference? I don't know if that's older or newer than what you're writing for. Basically any quoted field, like "domain" vs domain, it complained about. That, and `f.rdb$field_precision` simply did not exist.

**Comment by glennfu** [comment]
I just found this information on the "newness" of `field_precision`. Hopefully it's helpful! https://www.ibphoenix.com/resources/documents/design/doc_195

**Comment by rowland** [comment]
field_precision came with ODS 10, which Firebird 1.5 used, so that shouldn't be a problem, unless you're somehow using a database with an older ODS, which should only be possible if you're still on Firebird 1.5. What does "gstat -h" give you?

It's sometimes necessary to double-quote column names when otherwise they would conflict with a reserved word. SQL in general and Firebird in particular are funny about such things. The query works for me in the Firebird 2.5.4 console (isql), with or without the double quotes, except for around "precision", which gives me:
```
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 160
-precision
```
Adding back the quotes resolves the issue. I notice you left that field out of your revised query. That may have silenced your error but it's likely to break things for other folks.

**Comment by glennfu** [comment]
Oh yeah I'm not considering this as a pull request, I definitely don't know what I'm doing here! The database I'm connecting to is remote, so I'm not sure how to run `gstat -h` on it. I do know the database is quite old, however. I've definitely tried with and without the double-quotes and it barks at any double-quotes. I had to remove them all or the queries wouldn't work.

**Comment by rowland** [comment]
Not liking any double quotes sounds like Firebird 1 or Interbase 6, but since you already established that the engine version is 2.5.0, I would have to conclude that the issue is one of the dialect used.

http://www.firebirdsql.org/manual/isql-dialects.html

Dialect 1 was the legacy, pre-SQL-92 dialect. Dialect 2 was transitional. Dialect 3 is the only one supported by activerecord-fb-adapter. Some clients allow you to select a different dialect than the database's default for the scope of the connection, but neither activerecord-fb-adatper nor the underlying native gem fb support changing the dialect.

If possible, get the database's dialect changed.

http://www.firebirdsql.org/manual/gfix-dialect.html

Otherwise, you're looking at developing and maintaining a custom fork of activerecord-fb-adapter.

**Comment by glennfu** [comment]
I only have read-only access to the database, no permission to change anything or else I might risk breaking the app that depends on it. I guess a custom fork is where I'll play! Luckily I haven't run into any other problems. Everything else I've tried has been working great.
