### ISSUE TITLE
Error on bundle install

### ISSUE THREAD

**Issue by e-belair** [rowland/activerecord-fb-adapter#78]
Hi i get this error on bundle install
(using rails 3.2.22.5, ruby 2.4.3)

```
manu@manu-ThinkPad-X230:~/www/railsFbTest$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies....
Using rake 12.3.0
Using concurrent-ruby 1.0.5
Using i18n 0.9.5
Using multi_json 1.13.1
Using activesupport 3.2.22.5
Using builder 3.0.4
Using activemodel 3.2.22.5
Using erubis 2.7.0
Using journey 1.0.4
Using rack 1.4.7
Using rack-cache 1.7.1
Using rack-test 0.6.3
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.2.3
Using actionpack 3.2.22.5
Using mime-types 1.25.1
Using polyglot 0.3.5
Using treetop 1.4.15
Using mail 2.5.5
Using actionmailer 3.2.22.5
Using arel 3.0.3
Using tzinfo 0.3.53
Using activerecord 3.2.22.5
Fetching fb 0.9.0
Installing fb 0.9.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/manu/.gem/ruby/2.4.3/gems/fb-0.9.0
/home/manu/.rubies/ruby-2.4.3/bin/ruby -r ./siteconf20180307-3974-fyz1p2.rb extconf.rb
checking for isc_attach_database() in -lfbclient... no
checking for isc_attach_database() in -lgds... no
creating Makefile

current directory: /home/manu/.gem/ruby/2.4.3/gems/fb-0.9.0
make "DESTDIR=" clean

current directory: /home/manu/.gem/ruby/2.4.3/gems/fb-0.9.0
make "DESTDIR="
compiling fb.c
fb.c:41:10: fatal error: ibase.h: Aucun fichier ou dossier de ce type
 #include <ibase.h>
          ^~~~~~~~~
compilation terminated.
Makefile:241 : la recette pour la cible « fb.o » a échouée
make: *** [fb.o] Erreur 1

make failed, exit code 2

Gem files will remain installed in /home/manu/.gem/ruby/2.4.3/gems/fb-0.9.0 for inspection.
Results logged to /home/manu/.gem/ruby/2.4.3/extensions/x86_64-linux/2.4.0-static/fb-0.9.0/gem_make.out

An error occurred while installing fb (0.9.0), and Bundler cannot continue.
Make sure that `gem install fb -v '0.9.0'` succeeds before bundling.

In Gemfile:
  activerecord-fb-adapter was resolved to 1.0.3, which depends on
    fb
```

**Comment by e-belair** [comment]
Error corrected…

**Comment by guilhermemvo** [comment]
Hi, how did you fix it?

**Comment by e-belair** [comment]
Sorry, I don't remember. Maybe by installing missing library that provide ibase.h ...

**Comment by guilhermemvo** [comment]
@e-belair, tanks for reply! In my case I using Fedora 28, and apply this steps:

```
dnf install firebird
dnf install firebird-devel
dnf install libfbclient2-devel
ln -s /usr/include/firebird/ibase.h  /usr/include/ibase.h
```

follow this reference: https://github.com/rowland/fb/issues/62

**Comment by meskirian** [comment]
got same error with '**gem i fb**' on **ubuntu** 18.04(used to **rbenv**)

> ERROR:  Error installing fb:
> 	ERROR: Failed to build gem native extension.
> 
> ...
> 
> compiling fb.c
> fb.c:41:10: fatal error: ibase.h: No such file or directory
>  #include <ibase.h>
> 

fixed with '**sudo apt install libfbclient2 firebird-dev**'

**Comment by danilogomes** [comment]
Hi! I have a problem when run **bundle install** gem in any ruby ​​version. Can someone help me?

`Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/ferrujao/.rvm/rubies/ruby-2.3.3/bin/$(RUBY_BASE_NAME)
	--with-firebird-dir
	--without-firebird-dir
	--with-firebird-include
	--without-firebird-include=${firebird-dir}/include
	--with-firebird-lib
	--without-firebird-lib=${firebird-dir}/lib
	--with-fbclientlib
	--without-fbclientlib
/Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:90:in `block in <main>'
	from extconf.rb:90:in `each'
	from extconf.rb:90:in `find'
	from extconf.rb:90:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ferrujao/.rvm/gems/ruby-2.3.3/extensions/x86_64-darwin-19/2.3.0/fb-0.9.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ferrujao/.rvm/gems/ruby-2.3.3/gems/fb-0.9.0 for inspection.
Results logged to /Users/ferrujao/.rvm/gems/ruby-2.3.3/extensions/x86_64-darwin-19/2.3.0/fb-0.9.0/gem_make.out`


**### This is what the cat command shows:**
**cat  /Users/ferrujao/.rvm/gems/ruby-2.3.3/extensions/x86_64-darwin-19/2.3.0/fb-0.9.0/mkmf.log**

`"gcc -o conftest -I/Users/ferrujao/.rvm/rubies/ruby-2.3.3/include/ruby-2.3.0/x86_64-darwin19 -I/Users/ferrujao/.rvm/rubies/ruby-2.3.3/include/ruby-2.3.0/ruby/backward -I/Users/ferrujao/.rvm/rubies/ruby-2.3.3/include/ruby-2.3.0 -I.  -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I/Library/Frameworks/Firebird.framework/Headers  -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens  -fno-common -pipe -DOS_UNIX conftest.c  -L. -L/Users/ferrujao/.rvm/rubies/ruby-2.3.3/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib -framework Firebird     -lruby.2.3.0  -lpthread -ldl -lobjc "
ld: framework not found Firebird
clang: error: linker command failed with exit code 1 (use -v to see invocation)
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */`
